---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: selfsigned-wildcard-cert
  namespace: openshift-ingress
spec:
  secretName: selfsigned-wildcard-cert
  duration: 24h0m0s
  renewBefore: 1h30m0s
  subject:
    organizations:
      - blinker
  usages:
    - server auth
    - client auth
  dnsNames:
  - .apps.{{ .Values.name }}.{{ .Values.baseDomain }}
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
