= GitOps

NOTE: You can see an example workflow that uses this repo for GitOps link:https://github.com/r3dact3d/OCP4-Deploy/blob/main/.github/workflows/gitops.yaml[r3dact3d/OCP4-Deploy]

== Content

* <<Hub Cluster, Hub Cluster>>
* <<Managed Cluster Onboarding, Managed Cluster Onboarding>>
* <<Applicationsets, Applicationsets>>
* <<Labels, Labels>>

----
GitOps/
├─ appsets/
├─ cluster-onboarding/
├─ common-base/
│  ├─ openshift-config
│  ├─ openshift-monitoring
│  ├─ openshift-ingress-operator
│  ├─ openshift-compliance
│  ├─ cert-manager
├─ gitops-cluster/
├─ README.adoc
----
    
== Hub Cluster

. Install GitOps Operator

----
oc apply -f https://raw.githubusercontent.com/r3dact3d/gitops/main/gitops-cluster/gitops-operator.yaml -n openshift-operators
oc project openshift-gitops
oc adm policy add-cluster-role-to-user cluster-admin -z openshift-gitops-argocd-application-controller
----

[start=2]
. Optional for running GitOps service on Infra nodes

----
oc apply -f https://raw.githubusercontent.com/r3dact3d/gitops/main/gitops-cluster/gitopsservice.yaml
----

== Managed Cluster Onboarding

Leverage the link:https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/[Cluster] Generator to onboard managed clusters by storing parameters in link:https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters[secrets] 

. Create ArgoCD link:https://raw.githubusercontent.com/r3dact3d/gitops/main/gitops-cluster/cluster-onboarding-app.yaml[application] to keep kubernetes resources synced that are required for the Cluster generator 

----
oc create -f https://raw.githubusercontent.com/r3dact3d/gitops/main/gitops-cluster/cluster-onboarding-app.yaml
----

[start=2]
. link:https://github.com/r3dact3d/gitops/tree/main/cluster-onboarding[Onboard] new cluster by adding kubernetes secret to this repo 


== Applicationsets

link:https://github.com/r3dact3d/gitops/tree/main/appsets[Applicationsets] with cluster generator are used to manage the ArgoCD applications. The strategy here is to apply all applicationsets to hub cluster for the applicationset controller to monitor.
    
----
for i in $(ls appsets);do oc create -f $i;done
----

link:https://github.com/r3dact3d/gitops/tree/main/common-base[Cluster config] manifests logically grouped

== Labels

Kubernetes recommended link:https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels[labels].

