---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-app
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
        values:
          overlay: hub
  template:
    metadata:
      name: 'appset-{{cluster}}'
    spec:
      source:
        repoURL: 'https://github.com/r3dact3d/gitops'
        targetRevision: HEAD 
        path: 'appsets/applications/overlay/{{values.overlay}}'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
        
