---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day2-operations 
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: appsets/day2/overlay 
    repoURL: https://github.com/r3dact3d/gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
