---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ansible-automation-platform-appset
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-ansible-automation-platform'
    spec:
      destination:
        namespace: aap
        server: '{{url}}'
      project: default
      source:
        path: manifests-cluster/ansible-automation-platform
        repoURL: https://github.com/r3dact3d/gitops
        targetRevision: HEAD
      syncPolicy:
        applicationsSync: create-update
        automated:
          selfHeal: true