apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  finalizers:
    - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  name: default
  namespace: openshift-ingress-operator
spec:
  nodePlacement:
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/infra: ""
  clientTLS:
    clientCA:
      name: ''
    clientCertificatePolicy: ''
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ''
  replicas: 2
  tuningOptions: {}
  unsupportedConfigOverrides: null
