---
apiVersion: "logging.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: instance 
  namespace: openshift-logging 
spec:
  outputs:
   - name: splunk-server-secure 
     type: "fluentdForward"
     url: tls://prd-p-iv34h.splunkcloud.com:8088/services/collector/event
     secret:
       name: testsecret
   - name: splunk-server 
     type: "fluentdForward"
     url: tcp://prd-p-iv34h.splunkcloud.com:8088/services/collector/event
     secret:
       name: testsecret
  inputs: 
   - name: my-app-logs
     application:
        namespaces:
        - hello-houston-blinker-dev
        - openshift-file-integrity
  pipelines:
   - name: container-logs
     inputRefs:
     - my-app-logs
     - audit
     outputRefs:
     - splunk-server-secure
     - splunk-server
   - name: hedge-odds
     inputRefs:
     - infra
     - application
     outputRefs:
     - splunk-server
     - splunk-server-secure

