---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cost-management-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            demo: cost-management
        values:
          revision: HEAD
          env: dev

  template:
    metadata:
      name: '{{name}}-cost-management'
    spec:
      destination:
        namespace: costmanagement-metrics-operator
        server: '{{server}}'
      project: default
      source:
        repoURL: 'https://github.com/r3dact3d/gitops'
        path: 'common-base/cost-management/overlays/{{values.env}}'
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
