---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-registry-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            role: infra
  template:
    metadata:
      name: '{{name}}-openshift-registry'
    spec:
      destination:
        namespace: openshift-image-registry
        server: '{{server}}'
      project: default
      source:
        path: common-base/openshift-registry
        repoURL: https://github.com/r3dact3d/gitops
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
      - group: "*"
        kind: "*"
        managedFieldsManagers:
        - Go-http-client
