---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-registry-appset
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-openshift-registry'
    spec:
      destination:
        namespace: openshift-image-registry
        server: '{{url}}'
      project: default
      source:
        path: common-base/openshift-registry
        repoURL: https://github.com/r3dact3d/gitops
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
      - group: "*"
        kind: "*"
        managedFieldsManagers:
        - Go-http-client
